dist: bionic
sudo: false
language: python
env:
  - CASS_DRIVER_NO_CYTHON=1
matrix:
  include:
    - python: "3.7"
    - python: "3.8"
cache:
  - pip
install:
  - pip install tox-travis
script:
  - tox
